### ISSUE TITLE
SIP Sofia Answers with "udp too long trying TCP Instead"

### ISSUE THREAD

**Issue by haeferer** [davehorton/simple-sip-proxy#5]
Hi, 
Thanx for your great work. 

We try to use the SIP Proxy as a Starting point for drachtio.

* OPTION Ping for Proxy Server is working fine.

If we try to send an INVITE it fails. Within the DrachtIO Server log we see a line "udp too long, use tcp instead". Unfortunatly our SIP Provider does not support TCP :(

Is it possible to force UDP (we already added "transport=udp") over TCP, or increase the message size?

Thx again

Andreas

**Comment by davehorton** [comment]
hi there.  Yes - you can force UDP in this scenario.  The issue is that the underlying sofia sip stack by default switches to TCP if the body > 1333 bytes.  To set this to a higher level, in your dachtio.conf.xml you can set the higher limit, e.g.
```
<sip>
    <udp-mtu>4096</udp-mtu>
  </sip>
```

See relevant details [here](https://drachtio.org/docs/drachtio-server#udp-mtu), which was a feature added in release 0.7.3 so make sure you are running a recent version.

**Comment by davehorton** [comment]
This application is pretty old, and while I think it should still work I have updated the framework pretty substantially since it was written.  I think I should update this example, which I will try to do in the next day or two.

**Comment by haeferer** [comment]
Wow, thx for the Fast answer! 
We had created our first Proxy Solution using OpenSips (which works, but opensips scripting is very "strange" ;) )

Now we try to port our system to drachtio-srf.  
Would be very nice if you could update this sample (or show us how to do this / how we could help you)

I will also try to build a .d.ts TypeDefinition for your libary, since we are using typescript on our site (this speeds up usage of a libary a lot)

Cu 

Andreas

**Comment by haeferer** [comment]
Solved (use --mtu parameter)

**Comment by haeferer** [comment]
closing
